sudo: false
language: python
python:
    - "2.7"
install: "pip install -r requirements.txt && pip install tox tox-travis"
script: -e $TOX_ENV
env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-djangomaster
matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-djangomaster
